### ISSUE TITLE
optionally handle SIGHUP to terminate child processes

### ISSUE THREAD

**Issue by brenmar** [jaz303/spinup#5]
At present if the terminal window in which spinup is started is closed the child processes will remain, this is fine for daemon processes, but common usage would want you to be able to optionally terminate these processes if the terminal window or application (IDE for example) was closed.

This can be done by optionally handling the 'SIGHUP' interrupt in that same way that 'SIGINT' is currently handled. Using a `--no-daemon` flag to run in this mode.

**Comment by brenmar** [comment]
I looked at implementing a PR for this as it's pretty easy, but your current argument parser is very simple and does not handle un-argumented flags, and I don've have the time to rewrite your argument parser. Should be pretty easy to implement

add this to `cli.js`
```
function handleSigint() {
	exiting = true;
	process.stderr.write("sending SIGINT to all children...\n");
	if (instance) {
		instance.kill();
	}
}

process.on('SIGINT', handleSigint);

if (config.noDaemon) {
	process.on('SIGHUP', handleSigint);
}
```
And just handle the parsing of the `--no-daemon` flag in the `get-cli-config.js`. You might want to switch to one of the cli argument parsing libs.

**Comment by jaz303** [comment]
I think I would prefer the opposite - say, a `--daemon` flag to explicitly disable the `SIGHUP` handler. Is there any reason this is a bad idea?

**Comment by brenmar** [comment]
I also prefer that approach - it's my usual use case. I only suggested the `--no-daemon` approach to not change the current behaviour by default if people were using it commonly as a daemon starter.

**Comment by jaz303** [comment]
Same here. I'd argue the current behaviour is a bug as spinup is not intended as a daemon launcher. I'll get that change integrated tonight.
